CREATE TABLE INSTRUTOR (
  ID_INSTRUTOR INTEGER UNSIGNED  NOT NULL  ,
  NOME VARCHAR(255)  NULL   AUTO_INCREMENT,
  SOBRENOME VARCHAR(255)  NULL  ,
  EMAIL VARCHAR(255)  NULL    ,
PRIMARY KEY(ID_INSTRUTOR));

CREATE TABLE CURSO (
  ID_CURSO INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  INSTRUTOR_ID_INSTRUTOR INTEGER UNSIGNED  NOT NULL  ,
  TITULO VARCHAR(255)  NULL  ,
  DESCRIÇAO VARCHAR(255)  NULL  ,
  NIVEL_DE_DIFICULDADE VARCHAR(255)  NULL  ,
  POPULARIDADE VARCHAR(255)  NULL    ,
PRIMARY KEY(ID_CURSO)  ,
INDEX CURSO_FKIndex1(INSTRUTOR_ID_INSTRUTOR));

CREATE TABLE ALUNO (
  ID_ALUNO INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  NOME VARCHAR(255)  NULL  ,
  SOBRENOME VARCHAR(255)  NULL  ,
  EMAIL VARCHAR(255)  NULL    ,
PRIMARY KEY(ID_ALUNO));

CREATE TABLE INSCRICAO (
  ID_INSCRICAO INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  CURSO_ID_CURSO INTEGER UNSIGNED  NOT NULL  ,
  ALUNO_ID_ALUNO INTEGER UNSIGNED  NOT NULL  ,
  DATA_INSCRICAO VARCHAR(255)  NULL  ,
  STATUSS VARCHAR(255)  NULL    ,
PRIMARY KEY(ID_INSCRICAO)  ,
INDEX INSCRICAO_FKIndex1(ALUNO_ID_ALUNO)  ,
INDEX INSCRICAO_FKIndex2(CURSO_ID_CURSO));

